# Generated by Django 5.0.3 on 2024-12-03 09:00

from django.db import migrations
from load_data import load_customer_data,load_loan_data

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_customer_data),
        migrations.RunPython(load_loan_data)
    ]
